### ISSUE TITLE
1554G4442 / 1554G4442-8 / 246L17287 都尚未出現在 api 中

### ISSUE THREAD

**Issue by kiang** [g0v/api.ly#69]
請參考：
https://github.com/g0v/ly.g0v.tw/issues/184

1554G4442-8
* http://lci.ly.gov.tw/LyLCEW/agenda1/02/pdf/08/06/16/LCEWA01_080616_00249.pdf

246L17287
* http://lci.ly.gov.tw/LyLCEW/agenda1/02/pdf/08/06/14/LCEWA01_080614_00008.pdf
* http://misq.ly.gov.tw/MISQ/IQuery/misq5000QueryBillDetail.action?billNo=1031205070200200
* http://lis.ly.gov.tw/lgcgi/ttsweb?@@B194F2C1C1C377B5C563

**Comment by clkao** [comment]
they should be there now.
